FROM node:22-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npx nx build sumicare-web --configuration=production

FROM node:22-alpine
RUN npm install -g serve
WORKDIR /app
COPY --from=build /app/dist/apps/sumicare-web/browser ./dist
EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]