package com.sumicare.cashier.dto;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

public record OrderResponse(
        UUID id,
        UUID bookingId,
        UUID treatmentSlipId,
        UUID cashierUserId,
        String cashierDisplayName,
        String clientNickname,
        UUID clientId,
        String serviceName,
        String orNumber,
        String referenceNumber,
        String notes,
        BigDecimal subtotal,
        BigDecimal discount,
        BigDecimal total,
        BigDecimal amountPaid,
        BigDecimal balance,
        String status,
        OffsetDateTime createdAt,
        OffsetDateTime completedAt,
        OffsetDateTime finishedAt,
        OffsetDateTime cancelledAt,
        String cancelledReason,
        String transactorName,
        boolean groupBooking,
        boolean weekend,
        String roomType,
        BigDecimal roomTypeCharge,
        boolean sessionCompleted,
        boolean couplePackage,
        List<OrderItemResponse> items
) {}
